### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by stvnbash** [harshhhdev/harshhhdev.github.io#16]
Hi Harsh!  Your portfolio site is awesome!  I'm referencing your code, especially that for Framer Motion, as I'm building out my portfolio.

I found an issue with the link to create an issue from your 404 page.  Oh the irony!  Try this url instead: https://github.com/harshhhdev/harshhhdev.github.io/issues/new

**Comment by harshhhdev** [comment]
Hello @stvnbash :wave: 

I really appreciate the nice comments :heart: -- for the link, I just noticed, I've done `harshhhdev.github.io/issues.new` instead of `harshhhdev.github.io/issues/new`. 

Thanks for pointing that out! Have a nice week.
