### ISSUE TITLE
Make website responsive. 

### ISSUE THREAD

**Issue by harshhhdev** [harshhhdev/harshhhdev.github.io#2]
![image](https://user-images.githubusercontent.com/69592270/98620490-5ede4180-22d3-11eb-89f7-96555416c011.png)

This screenshot doesn't require an explaination for this issue... the website looks terrible on phones.

**Comment by FrontEndDev-Arhan** [comment]
#

> ![image](https://user-images.githubusercontent.com/69592270/98620490-5ede4180-22d3-11eb-89f7-96555416c011.png)
> 
> This screenshot doesn't require an explaination for this issue... the website looks terrible on phones.

Yes, it will look way better after a some fundamental changes. I will look into it. You can assign the issue to me.

**Comment by harshhhdev** [comment]
@FrontEndDev-Arhan 

Sorry, it was taking too long. I made it responsive by myself as I saw that you had not begun working on it.

I appreciate you wanting to help, there are other issues which you can work on.
