### ISSUE TITLE
Add links

### ISSUE THREAD

**Issue by harshhhdev** [harshhhdev/harshhhdev.github.io#3]
There are no links right now on the buttons. They are just blank and don't link to anything.

**Comment by Strigssson** [comment]
Hello, I would like to contribute on this issue, if u can tell me closer which buttons u mean and to which links they have to refer

**Comment by harshhhdev** [comment]
Sure, here is what I mean

Logos on the about page --

Twitter - https://twitter.com/HarshhhDev
Dribble (the basketball logo) https://dribbble.com/harshhhdev
Dev.to (the dev logo) https://dev.to/harshhhdev
Itch.io (the house with the controller in it) https://hypehex.itch.io/
GitHub - https://github.com/harshhhdev
Linkedin - https://www.linkedin.com/in/harsh-singh-5ba6b31b8/

**Comment by harshhhdev** [comment]
I can do the proejct ones by myself.

Though if you'd like to do them, feel free.

Can you just wrap all of the "github" logos and things in an `a` element? if so, that'd be great

**Comment by harshhhdev** [comment]
I mean 

![image](https://user-images.githubusercontent.com/69592270/98844867-f39f8700-241a-11eb-9018-a3d5d6fe2b20.png)

These things ^^

Just wrap them in an `a` element with an empty link. I'll fill them up :)

**Comment by harshhhdev** [comment]
I've assigned the issue to you. Feel free to work on it

**Comment by Strigssson** [comment]
Created pull request (hope created it in good way) :D

**Comment by harshhhdev** [comment]
@Strigssson crap. I almost forgot to say this, 

can you add a _blank to all the links?

**Comment by harshhhdev** [comment]
If you create a new PR for it, I'll merge it right in.

**Comment by Strigssson** [comment]
yes, no problem in a few minutes
